UPDATE_DEPLOY_Debug

diff --git a/.github/workflows/main_uaifly.yml b/.github/workflows/main_uaifly.yml
--- a/.github/workflows/main_uaifly.yml
+++ b/.github/workflows/main_uaifly.yml
@@ -14,7 +14,7 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Cache Node.js modules
-        uses: actions/cache@v3
+        uses: actions/cache@v4  # Atualizado para v4
         with:
           path: ~/.npm
           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
@@ -22,7 +22,7 @@ jobs:
             ${{ runner.os }}-node-
 
       - name: Set up Node.js version
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4  # Atualizado para v4
         with:
           node-version: '20.x'
 
@@ -46,8 +46,11 @@ jobs:
           tar -czf ./artifacts/frontend.tar.gz -C ./frontend .
         shell: bash
 
+      - name: List files after creating artifact
+        run: ls -la artifacts
+
       - name: Upload artifact for deployment job
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4  # Atualizado para v4
         with:
           name: node-app
           path: ./artifacts/frontend.tar.gz
@@ -61,15 +64,19 @@ jobs:
 
     steps:
       - name: Download artifact from build job
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4  # Atualizado para v4
         with:
           name: node-app
+          path: ./artifacts  # Adicionado path para especificar onde baixar o artefato
 
       - name: List files for debugging
-        run: ls -l
+        run: ls -la
+
+      - name: List files in artifacts directory for debugging
+        run: ls -la ./artifacts
 
       - name: Verify artifact presence
-        run: test -f ./artifacts/frontend.tar.gz
+        run: test -f ./artifacts/frontend.tar.gz || { echo "Artifact not found"; exit 1; }
 
       - name: Unzip artifact
         run: |
@@ -78,7 +85,7 @@ jobs:
         shell: bash
 
       - name: 'Login to Azure'
-        uses: azure/login@v1
+        uses: azure/login@v2  # Atualizado para v2
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
       
